=== BackupTheBerlios/freibier/FiBuServer/spec/xmlrpc-interface.dtd
<!ELEMENT interface (description,error*,module+)>
<!ATTLIST interface name CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT error (#PCDATA)>
<!ATTLIST error code    CDATA #REQUIRED>
<!ATTLIST error name    CDATA #REQUIRED>
<!ATTLIST error comment CDATA #IMPLIED> 

<!ELEMENT module (description,properties,error*,function+)>
<!ATTLIST module name CDATA #REQUIRED>

<!ELEMENT properties ((bool|int|date|string|base64)+)>
<!ATTLIST properties objectid CDATA #REQUIRED>

<!ELEMENT bool EMPTY>
<!ATTLIST bool name    CDATA                     #REQUIRED>
<!ATTLIST bool read    (explicit|implicit|no)    #REQUIRED>
<!ATTLIST bool query   (yes|no)                  #REQUIRED>
<!ATTLIST bool write   (yes|once|no)             #REQUIRED>
<!ATTLIST bool value   (optional|mandatory|auto) #REQUIRED>
<!ATTLIST bool comment CDATA                     #IMPLIED>

<!ELEMENT int EMPTY>
<!ATTLIST int name    CDATA                     #REQUIRED>
<!ATTLIST int read    (explicit|implicit|no)    #REQUIRED>
<!ATTLIST int query   (yes|no)                  #REQUIRED>
<!ATTLIST int write   (yes|once|no)             #REQUIRED>
<!ATTLIST int value   (optional|mandatory|auto) #REQUIRED>
<!ATTLIST int comment CDATA                     #IMPLIED>

<!ELEMENT date EMPTY>
<!ATTLIST date name    CDATA                     #REQUIRED>
<!ATTLIST date read    (explicit|implicit|no)    #REQUIRED>
<!ATTLIST date query   (yes|no)                  #REQUIRED>
<!ATTLIST date write   (yes|once|no)             #REQUIRED>
<!ATTLIST date value   (optional|mandatory|auto) #REQUIRED>
<!ATTLIST date comment CDATA                     #IMPLIED>

<!ELEMENT string EMPTY>
<!ATTLIST string name    CDATA                     #REQUIRED>
<!ATTLIST string read    (explicit|implicit|no)    #REQUIRED>
<!ATTLIST string query   (yes|no)                  #REQUIRED>
<!ATTLIST string write   (yes|once|no)             #REQUIRED>
<!ATTLIST string value   (optional|mandatory|auto) #REQUIRED>
<!ATTLIST string comment CDATA                     #IMPLIED>

<!ELEMENT base64 EMPTY>
<!ATTLIST base64 name    CDATA                     #REQUIRED>
<!ATTLIST base64 read    (explicit|implicit|no)    #REQUIRED>
<!ATTLIST base64 query   (yes|no)                  #REQUIRED>
<!ATTLIST base64 write   (yes|once|no)             #REQUIRED>
<!ATTLIST base64 value   (optional|mandatory|auto) #REQUIRED>
<!ATTLIST base64 comment CDATA                     #IMPLIED>

<!ELEMENT function (description,error*)>
<!ATTLIST function name     CDATA    #REQUIRED>
<!ATTLIST function read     (yes|no) #REQUIRED>
<!ATTLIST function where    (yes|no) #REQUIRED>
<!ATTLIST function order    (yes|no) #REQUIRED>
<!ATTLIST function write    (yes|no) #REQUIRED>
<!ATTLIST function objectid (yes|no) #REQUIRED>
<!ATTLIST function result   (yes|no) #REQUIRED>
<!ATTLIST function comment  CDATA    #IMPLIED>

=== BackupTheBerlios/freibier/FiBuServer/spec/xmlrpc-interface.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE interface SYSTEM "xmlrpc-interface.dtd">
<interface name="fibu">
  <description>Schnittstelle des Freibier-FiBu-Servers</description>
  <error name="MISSING_RIGHTS" code="10000">Fehlende Rechte für diese Funktion.</error>
  <error name="DATABASE_ERROR" code="10010">Fehler beim Datenbankzugriff.</error>
  <error name="XMLRPC_ERROR" code="10020">Falscher Name für XMLRPC-Funktion.</error>
  <module name="customer">
    <description>Das Modul customer verwaltet die Firmenstammdaten</description>
    <properties objectid="{custid}">
      <int    name="custid"      	read="implicit" query="yes" write="no"   value="auto"/>
      <string name="firma"  		read="implicit" query="yes" write="yes"  value="mandatory"/>
      <int    name="bilanzkonto" 	read="implicit" query="yes" write="yes"  value="mandatory"/>
      <int    name="guvkonto"       read="implicit" query="yes" write="yes"  value="mandatory"/>
      <string name="jahr"       	read="implicit" query="yes" write="yes"  value="mandatory"/>
      <string name="periode"        read="implicit" query="yes" write="yes"  value="mandatory"/>
      <date   name="since"       	read="explicit" query="no"  write="no"   value="auto"/>
      <date   name="lastupdate" 	read="explicit" query="no"  write="no"   value="auto"/>
    </properties>
    <error name="ERR_CUSTOMER" code="10101">Cust-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>Auflisten der Firmenstammdaten</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Ändern der Firmenstammdaten</description>
    </function>
  </module>
  <module name="mwst">
    <description>Das Modul mwst verwaltet die Mehrwertsteuersätze und ordnet Konten zu</description>
    <properties objectid="mwstid">
      <int    name="mwstid"          read="implicit" query="yes" write="no"    value="auto"/>
      <int    name="mwstsatz"        read="implicit" query="yes" write="once"  value="mandatory"/>
      <string name="mwsttext"        read="implicit" query="yes" write="yes"   value="mandatory"/>
      <int    name="mwstkontosoll"   read="implicit" query="yes" write="once"  value="mandatory"/>
      <int    name="mwstkontohaben"  read="implicit" query="yes" write="once"  value="mandatory"/>
      <bool   name="mwstsatzaktiv"   read="explicit" query="yes" write="yes"   value="auto"/>
    </properties>
    <error name="ERR_TAX" code="10201">MWSt-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>MWSt-Sätze lesen</description>
    </function>
    <function name="add" read="no" where="no" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion add fügt einen neuen MWSt-Satz ein</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion update ändert Attribute eines MWSt-Satzes</description>
    </function>
  </module>
  <module name="konto">
    <description>Das Modul konto verwaltet die Buchhaltungskonten</description>
    <properties objectid="{kontoid}">
      <int    name="kontoid"  		read="implicit" query="yes" write="no"    value="auto"/>
      <string name="kontonr"  		read="implicit" query="yes" write="yes"   value="mandatory"/>
      <string name="bezeichnung" 	read="implicit" query="yes" write="yes"   value="mandatory"/>
      <int    name="mwstid"         read="implicit" query="yes" write="yes"   value="mandatory"/>
      <int    name="oberkonto"      read="implicit" query="yes" write="yes"   value="optional"/>
      <bool   name="istsoll"        read="implicit" query="yes" write="yes"   value="auto"/>
      <bool   name="isthaben"		read="implicit" query="yes" write="yes"   value="auto"/>
      <bool   name="istaktiv"		read="implicit" query="yes" write="yes"   value="auto"/>
      <bool   name="istpassiv"		read="implicit" query="yes" write="yes"   value="auto"/>
      <bool   name="istaufwand"		read="implicit" query="yes" write="yes"   value="auto"/>
      <bool   name="istertrag"		read="implicit" query="yes" write="yes"   value="auto"/>
    </properties>
    <error name="ERR_LEDGER" code="10301">Konto-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>Die Funktion list liefert eine Liste von Konten</description>
    </function>
    <function name="add" read="no" where="no" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion add fügt ein neues Konto ein</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion update ändert Attribute eines Kontos</description>
    </function>
    <function name="delete" read="no" where="yes" order="no" write="no" objectid="yes" result="no">
      <description>Die Funktion delete löscht Konten</description>
    </function>
  </module>
  <module name="journal">
    <description>Das Modul journal verwaltet die Buchungsjournale</description>
    <properties objectid="{jourid}">
      <int    name="jourid"  		read="implicit" query="yes" write="no"    value="auto"/>
      <string name="journr"  		read="implicit" query="yes" write="yes"   value="mandatory"/>
      <string name="jahr"       		read="implicit" query="yes" write="yes"   value="mandatory"/>
      <string name="periode"        read="implicit" query="yes" write="yes"   value="mandatory"/>
      <date   name="since"       	read="implicit" query="yes" write="yes"   value="auto"/>
      <date   name="lastupdate" 		read="explicit" query="yes" write="no"    value="auto"/>
      <bool   name="absummiert"		read="implicit" query="yes" write="yes"   value="auto"/>
    </properties>
    <error name="ERR_JOURNAL" code="10401">Journal-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>Die Funktion list liefert eine Liste von Journalen</description>
    </function>
    <function name="add" read="no" where="no" order="no" write="yes" objectid="yes" result="yes">
      <description>Die Funktion add legt ein neues Journal an</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion update ändert Attribute eines Journals</description>
    </function>
    <function name="delete" read="no" where="yes" order="no" write="no" objectid="yes" result="no">
      <description>Die Funktion delete löscht Journale</description>
    </function>
  </module>
  <module name="buchung">
    <description>Das Modul buchung verwaltet Buchungen</description>
    <properties objectid="{buchid}">
      <int    name="buchid"  		read="implicit" query="yes" write="no"    value="auto"/>
      <string name="belegnr"  		read="implicit" query="yes" write="yes"   value="mandatory"/>
      <string name="buchungstext"   read="implicit" query="yes" write="yes"   value="mandatory"/>
      <int    name="jourid"         read="implicit" query="yes" write="yes"   value="mandatory"/>
      <date   name="valuta"       	read="implicit" query="yes" write="yes"   value="mandatory"/>
      <date   name="erfassung" 		read="explicit" query="yes" write="no"    value="auto"/>
    </properties>
    <error name="ERR_ACCOUNTING" code="10501">Buchungs-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>Die Funktion list liefert eine Liste von Buchungen</description>
    </function>
    <function name="add" read="no" where="no" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion add legt eine neue Buchung an</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion update ändert Attribute einer Buchung</description>
    </function>
    <function name="delete" read="no" where="yes" order="no" write="no" objectid="yes" result="no">
      <description>Die Funktion delete löscht Buchungen</description>
    </function>
  </module>
  <module name="buchungszeile">
    <description>Das Modul buchungszeile verwaltet Buchungszeilen</description>
    <properties objectid="{buzlid}">
      <int    name="buzlid"  		read="implicit" query="yes" write="no"    value="auto"/>
      <int    name="buchid"  		read="implicit" query="yes" write="once"  value="mandatory"/>
      <int    name="kontoid"  		read="implicit" query="yes" write="once"  value="mandatory"/>
      <int    name="betrag"         read="implicit" query="yes" write="yes"   value="mandatory"/>
      <bool   name="soll"        	read="implicit" query="yes" write="yes"   value="mandatory"/>
      <bool   name="haben"			read="implicit" query="yes" write="yes"   value="mandatory"/>
    </properties>
    <error name="ERR_ENTRY" code="10601">Buchungszeile-Fehler Unbekannt</error>
    <function name="list" read="yes" where="yes" order="yes" write="no" objectid="yes" result="yes">
      <description>Die Funktion list liefert eine Liste von Buchungen</description>
    </function>
    <function name="add" read="no" where="no" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion add legt eine neue Buchung an</description>
    </function>
    <function name="update" read="no" where="yes" order="no" write="yes" objectid="yes" result="no">
      <description>Die Funktion update ändert Attribute einer Buchung</description>
    </function>
    <function name="delete" read="no" where="yes" order="no" write="no" objectid="yes" result="no">
